//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PadCRM.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class Department
    {
        public Department()
        {
            this.Permissions = new HashSet<Permissions>();
            this.Member = new HashSet<Member>();
            this.Notice = new HashSet<Notice>();
            this.MediaRequire = new HashSet<MediaRequire>();
            this.ContactRequire = new HashSet<ContactRequire>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [MaxLength(50)]
        [Display(Name = "部门名称")]
        public string Name { get; set; }

        [MaxLength(150)]
        [Display(Name = "部门描述")]
        public string Description { get; set; }

        public int LeaderID { get; set; }

        [Display(Name = "上级部门")]
        public int? PID { get; set; }

        [Display(Name = "部门代码")]
        public int Code { get; set; }

        [Display(Name = "类别级别")]
        public int Level { get; set; }

        [ScriptIgnore]
        public virtual Department PDepartment { get; set; }

        [ScriptIgnore]
        public virtual ICollection<Department> ChildDepartments { get; set; }

        public virtual ICollection<Permissions> Permissions { get; set; }

        public virtual ICollection<Member> Member { get; set; }

        public virtual ICollection<Notice> Notice { get; set; }

        public virtual ICollection<MediaRequire> MediaRequire { get; set; }

        public virtual ICollection<ContactRequire> ContactRequire { get; set; }
    }
}
