// <auto-generated />
namespace PadCRM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class eight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eight));
        
        string IMigrationMetadata.Id
        {
            get { return "201401130622068_eight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
