// <auto-generated />
namespace PadCRM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _12m : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12m));
        
        string IMigrationMetadata.Id
        {
            get { return "201401140211583_12m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
