// <auto-generated />
namespace PadCRM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Fine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fine));
        
        string IMigrationMetadata.Id
        {
            get { return "201401100220280_Fine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
