// <auto-generated />
namespace PadCRM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update1345 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update1345));
        
        string IMigrationMetadata.Id
        {
            get { return "201402250248018_update1345"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
