// <auto-generated />
namespace PadCRM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update134545 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update134545));
        
        string IMigrationMetadata.Id
        {
            get { return "201402250249146_update134545"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
